import type { ThemeManifest } from "./schema";

const base = {
  version: "1.0.0",
  author: "Dataarchy",
  builtIn: true,
  density: "comfortable" as const,
  widgets: { aiCore: "reactor" as const, graph: "hud" as const, alert: "pulse" as const },
};

export const builtInThemes: ThemeManifest[] = [
  {
    ...base,
    id: "aegis",
    name: "Aegis",
    description: "The default Dataarchy command environment: cool cyan intelligence, dark glass, and restrained cinematic motion.",
    category: "cinematic",
    tags: ["default", "cyan", "glass", "operations"],
    colors: { background: "#03070A", background2: "#071015", panel: "#071013", panelStrong: "#081217", text: "#D9F3F6", muted: "#7DA5AD", dim: "#4F7179", accent: "#62DFF4", accent2: "#B5F7FF", good: "#75E7B0", warn: "#F2BD69", bad: "#FF746C", info: "#74BFF8", line: "#27535B", glow: "#2EAEC1" },
    chrome: { border: "soft", pane: "glass", button: "glass", radius: 2 },
    effects: { motion: "subtle", glow: "medium", grid: true, scanlines: true, noise: false, vignette: true },
  },
  {
    ...base,
    id: "code-rain",
    name: "Code Rain",
    description: "Phosphor-green terminal futurism with cascading data-rain energy, deep blacks, and hacker-console geometry.",
    category: "terminal",
    tags: ["green", "terminal", "hacker", "code-rain"],
    colors: { background: "#010402", background2: "#031108", panel: "#031009", panelStrong: "#05160B", text: "#C9FFD2", muted: "#71B77E", dim: "#3C7148", accent: "#39FF6A", accent2: "#B9FFC8", good: "#71FF8B", warn: "#D4E65A", bad: "#FF6673", info: "#63E6A0", line: "#185F2B", glow: "#2BFF66" },
    chrome: { border: "sharp", pane: "terminal", button: "flat", radius: 0 },
    effects: { motion: "medium", glow: "medium", grid: true, scanlines: true, noise: true, vignette: true },
    widgets: { aiCore: "node", graph: "terminal", alert: "pulse" },
  },
  {
    ...base,
    id: "neon-grid-77",
    name: "Neon Grid 77",
    description: "High-energy neon command deck with yellow, cyan, and magenta accents, angular panels, and electric HUD feedback.",
    category: "cinematic",
    tags: ["neon", "yellow", "magenta", "cyberpunk", "angular"],
    colors: { background: "#07070A", background2: "#101016", panel: "#111118", panelStrong: "#17171F", text: "#F7F6EE", muted: "#A7A3B1", dim: "#6E697A", accent: "#F6E652", accent2: "#72F7FF", good: "#58F08B", warn: "#FFB145", bad: "#FF456E", info: "#63DDFF", line: "#5A5330", glow: "#E94CFF" },
    chrome: { border: "sharp", pane: "holographic", button: "angled", radius: 0 },
    effects: { motion: "high", glow: "high", grid: true, scanlines: true, noise: true, vignette: true },
    widgets: { aiCore: "reactor", graph: "hud", alert: "flash" },
  },
  {
    ...base,
    id: "federation-console",
    name: "Federation Console",
    description: "Warm segmented console design with orange, coral, plum, and slate surfaces optimized for calm operational readability.",
    category: "executive",
    tags: ["segmented", "orange", "plum", "console", "calm"],
    colors: { background: "#08090C", background2: "#10131A", panel: "#11141B", panelStrong: "#191D26", text: "#F7EEDC", muted: "#B3A690", dim: "#736B61", accent: "#F0A35B", accent2: "#F7C97C", good: "#A3D983", warn: "#F3C461", bad: "#E87567", info: "#A996D9", line: "#705542", glow: "#A76AA4" },
    chrome: { border: "segmented", pane: "flat", button: "segmented", radius: 18 },
    effects: { motion: "subtle", glow: "low", grid: false, scanlines: false, noise: false, vignette: false },
    widgets: { aiCore: "ring", graph: "clean", alert: "steady" },
  },
  {
    ...base,
    id: "ghost-station",
    name: "Ghost Station",
    description: "Cold blue tactical station aesthetic with quiet motion, ice-cyan instrumentation, and deep-space contrast.",
    category: "cinematic",
    tags: ["blue", "tactical", "space", "quiet"],
    colors: { background: "#03070C", background2: "#07111B", panel: "#09131D", panelStrong: "#0B1722", text: "#EAF8FF", muted: "#8EA8B8", dim: "#557182", accent: "#70D8FF", accent2: "#D7F4FF", good: "#92E2B9", warn: "#F0BF72", bad: "#FF7874", info: "#7EAFFF", line: "#27506A", glow: "#4AADE0" },
    chrome: { border: "soft", pane: "glass", button: "glass", radius: 6 },
    effects: { motion: "subtle", glow: "medium", grid: true, scanlines: false, noise: false, vignette: true },
    widgets: { aiCore: "reactor", graph: "hud", alert: "pulse" },
  },
  {
    ...base,
    id: "hologlass",
    name: "Hologlass",
    description: "Minimal translucent blue glass, generous spacing, low visual noise, and a polished near-future executive interface.",
    category: "executive",
    tags: ["glass", "minimal", "blue", "executive"],
    colors: { background: "#071017", background2: "#0B1821", panel: "#10222D", panelStrong: "#132A36", text: "#F2FAFD", muted: "#A3BBC7", dim: "#66808E", accent: "#7BDDF5", accent2: "#DDF9FF", good: "#9BE1BE", warn: "#F2C785", bad: "#F18482", info: "#8CBDF8", line: "#365E6D", glow: "#72D3EA" },
    chrome: { border: "rounded", pane: "glass", button: "glass", radius: 14 },
    effects: { motion: "subtle", glow: "low", grid: false, scanlines: false, noise: false, vignette: false },
    widgets: { aiCore: "orb", graph: "clean", alert: "steady" },
  },
  {
    ...base,
    id: "industrial-ops",
    name: "Industrial Ops",
    description: "Graphite machinery, hazard amber, steel-blue telemetry, and serious operator controls for pipelines and repair work.",
    category: "cinematic",
    tags: ["industrial", "amber", "graphite", "repair"],
    colors: { background: "#080909", background2: "#111313", panel: "#151817", panelStrong: "#1A1E1D", text: "#EDF0E9", muted: "#A6AAA1", dim: "#6B716B", accent: "#E6A64A", accent2: "#FFD28C", good: "#9AD17C", warn: "#F4B64E", bad: "#E9675B", info: "#77AFC4", line: "#5D4B2D", glow: "#C38131" },
    chrome: { border: "sharp", pane: "flat", button: "angled", radius: 1 },
    effects: { motion: "subtle", glow: "low", grid: true, scanlines: false, noise: true, vignette: true },
    widgets: { aiCore: "node", graph: "hud", alert: "flash" },
  },
  {
    ...base,
    id: "solar-command",
    name: "Solar Command",
    description: "Warm copper and ivory mission-control styling for executive demonstrations and long-form operational work.",
    category: "executive",
    tags: ["copper", "warm", "mission-control", "executive"],
    colors: { background: "#0A0806", background2: "#15100B", panel: "#1A140E", panelStrong: "#20180F", text: "#FFF3DD", muted: "#C7AD8D", dim: "#806D58", accent: "#E7A35B", accent2: "#FFE0A8", good: "#A9D785", warn: "#F0B55E", bad: "#E77465", info: "#83B7CA", line: "#6A4B31", glow: "#D98B45" },
    chrome: { border: "soft", pane: "glass", button: "segmented", radius: 8 },
    effects: { motion: "subtle", glow: "medium", grid: false, scanlines: false, noise: false, vignette: true },
    widgets: { aiCore: "ring", graph: "clean", alert: "steady" },
  },
  {
    ...base,
    id: "retro-terminal",
    name: "Retro Terminal",
    description: "Amber CRT command line nostalgia with blocky panels, scanlines, subdued glow, and dense power-user information design.",
    category: "terminal",
    tags: ["amber", "crt", "retro", "terminal"],
    density: "compact",
    colors: { background: "#060402", background2: "#110A03", panel: "#120B04", panelStrong: "#1A1006", text: "#F7D895", muted: "#B18B4D", dim: "#75582F", accent: "#FFB94E", accent2: "#FFE2A2", good: "#B8D56C", warn: "#F4B44D", bad: "#E86D55", info: "#C9935C", line: "#67431C", glow: "#E7972D" },
    chrome: { border: "sharp", pane: "terminal", button: "flat", radius: 0 },
    effects: { motion: "subtle", glow: "medium", grid: false, scanlines: true, noise: true, vignette: true },
    widgets: { aiCore: "node", graph: "terminal", alert: "steady" },
  },
  {
    ...base,
    id: "deep-void",
    name: "Deep Void",
    description: "Premium black-violet command space with indigo instrumentation, controlled bloom, and elegant low-light depth.",
    category: "cinematic",
    tags: ["violet", "indigo", "premium", "dark"],
    colors: { background: "#05040A", background2: "#0B0815", panel: "#100D1D", panelStrong: "#151125", text: "#F3EEFF", muted: "#A99EC0", dim: "#6C6282", accent: "#9C83FF", accent2: "#D9CFFF", good: "#8ED6AE", warn: "#E3B96C", bad: "#F06F83", info: "#7BA9FF", line: "#44356F", glow: "#7656E8" },
    chrome: { border: "soft", pane: "holographic", button: "glass", radius: 8 },
    effects: { motion: "medium", glow: "high", grid: true, scanlines: false, noise: false, vignette: true },
    widgets: { aiCore: "orb", graph: "hud", alert: "pulse" },
  },
  {
    ...base,
    id: "biosignal",
    name: "BioSignal",
    description: "Clinical-future command center with teal, medical blue, and soft green tuned for healthcare analytics and operational clarity.",
    category: "healthcare",
    tags: ["healthcare", "clinical", "teal", "clean"],
    colors: { background: "#03100F", background2: "#071918", panel: "#0A201F", panelStrong: "#0D2927", text: "#E9FBF7", muted: "#91BDB6", dim: "#5A817B", accent: "#58DFC8", accent2: "#C8FFF2", good: "#88E5A8", warn: "#F2C66E", bad: "#F07272", info: "#73BDF2", line: "#27645D", glow: "#3BCAB4" },
    chrome: { border: "rounded", pane: "glass", button: "segmented", radius: 10 },
    effects: { motion: "subtle", glow: "low", grid: true, scanlines: false, noise: false, vignette: false },
    widgets: { aiCore: "ring", graph: "clean", alert: "pulse" },
  },
];

export function getBuiltInTheme(id: string) {
  return builtInThemes.find((theme) => theme.id === id);
}
